// Auth

export const LOGIN_SET = 'LOGIN_SET';
export const LOGOUT_SET = 'LOGOUT_SET';
export const AUTH_SET = 'AUTH_SET';

// Building
export const BUILDING_SET = 'BUILDING_SET';
export const BUILDINGS_SET = 'BUILDINGS_SET';
export const BUILDING_PAGEABLE = 'BUILDING_PAGEABLE';
export const BUILDING_STATE_CLEAR = 'BUILDING_STATE_CLEAR';

// User

export const USER_SET = 'USER_SET';
export const USERS_SET = 'USERS_SET';
export const USER_PAGEABLE = 'USER_PAGEABLE';
export const USER_PROFILE = 'USER_PROFILE';
export const USER_STATE_CLEAR = 'USER_STATE_CLEAR';

// Building
export const CUSTOMER_SET = 'CUSTOMER_SET';
export const CUSTOMERS_SET = 'CUSTOMERS_SET';
export const CUSTOMER_PAGEABLE = 'CUSTOMER_PAGEABLE';
export const CUSTOMER_STATE_CLEAR = 'CUSTOMER_STATE_CLEAR';

// Transaction
export const TRANSACTION_SET = 'TRANSACTION_SET';
export const TRANSACTIONS_SET = 'TRANSACTIONS_SET';
export const TRANSACTION_STATE_CLEAR = 'TRANSACTION_STATE_CLEAR';

// Common

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';
